name: Test and build
on:
  push:
    branches:
      - '*'
env:
  NODE_ENV: development
  NODE_VERSION: 18
jobs:
  test-and-build:
    name: Test and build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Setup environment
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
      - name: Install dependencies
        working-directory: app
        run: npm ci
      - name: Syntax tests
        working-directory: app
        run: npm run lint
      - name: Unit tests
        working-directory: app
        run: npm run test
      - name: Build
        working-directory: app
        run: npm run build
